#!/bin/bash
# vim: sw=4
set -o errexit -o nounset -o pipefail -o noglob

project="$1"
year="$2"

if ! [ -d "${project}" ]; then
    die "Project directory '${project}' does not exist."
fi
cd "${project}"

if ! [ -d '.git' ]; then
    die "Missing '$(pwd)/.git'; maybe init-project."
fi

(
    stdlock 10

    umask 0007
    mkdir "${year}"
    chmod g+s "${year}"
    cd "${year}"
    git init --shared
    touch .gitignore .gitmodules
    git add .gitignore .gitmodules
    git commit -m 'init'
    cd ..

    # Commit parent dir if it contains a Git repo.
    if ! [ "$(git rev-parse --is-inside-work-tree 2>/dev/null)" = "true" ]; then
        echo "    SKIP commit super: not a git working copy"
    elif !  [ -f "$(git rev-parse --show-toplevel)/.gitmodules" ]; then
        echo "    SKIP commit super: missing .gitmodules"
    elif ! [ -w "$(git rev-parse --git-dir)" ]; then
        echo "    SKIP commit super: cannot write to Git dir."
    else
        echo "    COMMIT super"
        # Avoid permission denied if file owned by a different user.
        rm -f '.git/COMMIT_EDITMSG' || true
        git submodule add -- "./${year}" "${year}"
        git commit -m "${year}: init"
    fi
) 10<"$(stdlockdir)"

exitok
